version: '3.9'
services:
  server:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    command: ./server
    depends_on:
      - redis
      - jaeger

  # collector:
  #   image: otel/opentelemetry-collector:0.23.0
  #   command: "--config /etc/otel-config.yaml"
  #   volumes:
  #     - ./otel-config.yaml:/etc/otel-config.yaml

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:6831"

  redis:
    container_name: redis
    image: redis:6.2.7
    restart: unless-stopped
    ports:
      - "6387:6379"