version: '3.9'
services:
  accountserver:
    container_name: accountserver
    command: ./account-server
    build:
      context: ./
      dockerfile: accountserver/dockerfile
    ports:
      - "8002:8002"
    environment:
      REDIS_URL: redis:6379
    depends_on:
      - redis
      - jaeger
      - collector

  edgeserver:
    container_name: edgeserver
    command: ./edge-server
    build:
      context: ./
      dockerfile: edgeserver/dockerfile
    ports:
      - "8000:8000"
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@rabbit:5672/
      ACCOUNT_SERVER_URL: http://accountserver:8002
    depends_on:
      - redis
      - jaeger
      - collector
      - rabbitmq

  collector:
    container_name: collector
    image: otel/opentelemetry-collector:0.23.0
    command: "--config /etc/otel-config.yaml"
    volumes:
      - ./otel-config.prod.yaml:/etc/otel-config.yaml

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:6831"

  redis:
    container_name: redis
    image: redis:6.2.7
    restart: unless-stopped
    ports:
      - "6387:6379"
  
  rabbitmq:
    container_name: rabbit
    ports:
    - "15672:15672"
    - "5672:5672"
    image: "rabbitmq:3.8-management-alpine"