receivers:
 jaeger:
   protocols:
     thrift_compact:

processors:
 batch:

exporters:
 otlp:
   endpoint: tempo-eu-west-0.grafana.net:443
   headers:
     authorization: Basic <insert base65 of <id:api key> here>

service:
 pipelines:
   traces:
     receivers: [jaeger]
     processors: [batch]
     exporters: [otlp]